#!/bin/python
# coding: utf-8
from keystone_auth import OSClient
from tool import checkArgs, checkError, helpMsg
import requests, sys

#Get endpoint, passwd, critical, warning
args = checkArgs(sys.argv)
#print args

#Get Openstack auth token
token = OSClient('admin', args['passwd'], 'admin', 'http://' + args['endpoint'] + ':5000/v2.0').get_token()

#Get Neutron service list
header = {'X-Auth-Token': token}
r = requests.get('http://' + args['endpoint'] + ':9696/v2.0/agents.json', headers=header)
data = r.json()
checkError(data)
runningService = 0
#print data

#Check Neutron service state
for state in data['agents']:
	if state['alive'] == True:
		runningService += 1

if runningService < args['warning']  and runningService > args['critical']:
	print 'Neutron is Warning, running agents:', runningService
	sys.exit(1)
elif runningService < args['critical']:
	print 'Neutron is Critical, running agents:', runningService 
	sys.exit(2)
else:
	print 'Neutron is Ok, running agents:', runningService 
	sys.exit(0)
